# Generated by Django 2.2.4 on 2019-08-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190815_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
    ]
